apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: automatic
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"